services:
  - type: web
    name: duolingo-detector
    env: python
    buildCommand: ""
    startCommand: gunicorn -w 1 -b 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
